app/routes/zaposlenik_placa_routes.py
from flask import Flask, Blueprint, render_template, redirect, request
from app.interfaces.iroutes import IRoutes
from app.services.zaposlenik_placa_service import ZaposlenikPlacaService
from app.services.zaposlenik_service import ZaposlenikService
from app.router.routes import ZaposlenikPlacaRoutesEnum

class ZaposlenikPlacaRoutes(IRoutes):
    def __init__(self, app: Flask):
        self.app = app
        self.zaposlenik_placa_routes_bp = Blueprint('zaposlenik_placa_routes', __name__)
        self.zaposlenik_placa_service = ZaposlenikPlacaService(self.app)
        self.zaposlenik_service = ZaposlenikService(self.app)
        
    def register_routes(self):
        self.app.logger.info("Registering routes for ZaposlenikPlaca")
        self.app.logger.info(f"Registering route: {ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACE.value}")
        self.zaposlenik_placa_routes_bp.route(ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACE.value, methods=["GET"])(self.get_zaposlenik_place_months)
        self.app.logger.info(f"Registering route: {ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACE_MONTH.value}")
        self.zaposlenik_placa_routes_bp.route(ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACE_MONTH.value, methods=["GET"])(self.get_zaposlenik_place_by_month)
        self.app.logger.info(f"Registering route: {ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACE_ID.value}")
        self.zaposlenik_placa_routes_bp.route(ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACE_ID.value, methods=["GET"])(self.get_zaposlenik_placa)
        self.app.logger.info(f"Registering route: {ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACE_CREATE.value}")
        self.zaposlenik_placa_routes_bp.route(ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACE_CREATE.value, methods=["GET"])(self.create_zaposlenik_place)
        self.app.logger.info(f"Registering route: {ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACE_CREATED.value}")
        self.zaposlenik_placa_routes_bp.route(ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACE_CREATED.value, methods=["POST"])(self.created_zaposlenik_place)
        self.app.logger.info(f"Registering route: {ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACA_ALL.value}")
        self.zaposlenik_placa_routes_bp.route(ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACA_ALL.value, methods=["GET"])(self.get_zaposlenik_placa_all)
        self.app.register_blueprint(self.zaposlenik_placa_routes_bp)  
        
    def get_zaposlenik_place_months(self):
        try:
            data = self.zaposlenik_placa_service.get_zaposlenik_place_months()
            return render_template(self.app.router.get_template(ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACE.value), data=data)
        except Exception as e:
            self.app.logger.error(f"Error in get_zaposlenik_place_month: {e}")
            return "Internal Server Error", 500
        
    def get_zaposlenik_place_by_month(self):
        try:
            month = request.args.get('mjesec')
            month = f"{month}-01"
            data = self.zaposlenik_placa_service.get_zaposlenik_place_by_month(month)
            return render_template(self.app.router.get_template(ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACE_MONTH.value), data=data)
        except Exception as e:
            self.app.logger.error(f"Error in get_zaposlenik_place_by_month: {e}")
            return "Internal Server Error", 500
       
    def get_zaposlenik_placa(self, id):
        try:
            data = self.zaposlenik_placa_service.get_zaposlenik_placa(id)
            return render_template(self.app.router.get_template(ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACE_ID.value), data=data)
        except Exception as e:
            self.app.logger.error(f"Error in get_zaposlenik_placa: {e}")
            return "Internal Server Error", 500   
        
    def create_zaposlenik_place(self):
        try:
            data = self.zaposlenik_service.get_zaposlenici()
            return render_template(self.app.router.get_template(ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACE_CREATE.value), data=data)
        except Exception as e:
            self.app.logger.error(f"Error in create_zaposlenik_place: {e}")
            return "Internal Server Error", 500
        
    def created_zaposlenik_place(self):
        try:
            form = request.form
            month = form["mjesec"]
            month = f"{month}-01"
            
            for key, value in form.items():
                if key.startswith('iznos_place_'):
                    zaposlenik_id = key.split('_')[2]
                    iznos_place = value
                    id = self.zaposlenik_placa_service.insert_zaposlenik_placa(zaposlenik_id, iznos_place, month)
                    self.zaposlenik_placa_service.process_zaposlenik_placa_transaction(id)
            
            return redirect(ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACE.value)
        except Exception as e:
            self.app.logger.error(f"Error in created_zaposlenik_place: {e}")
            return "Internal Server Error", 500
        
    def get_zaposlenik_placa_all(self):
        try:
            data = self.zaposlenik_placa_service.get_zaposlenik_place_all()
            return render_template(self.app.router.get_template(ZaposlenikPlacaRoutesEnum.ZAPOSLENIK_PLACA_ALL.value), data=data)
        except Exception as e:
            self.app.logger.error(f"Error in get_zaposlenik_placa_all: {e}")
            return "Internal Server Error", 500

app/templates/pages/zaposlenik_placa/zaposlenik_placa.html
{% extends "index.html" %} {% block content %}
<h2>Detalji zaposlenik plaća:</h2>
<div class="card">
  <div class="single-item-details">
    <div class="details-item">
      <label>ID:</label>
      <span>{{data.id}}</span>
    </div>
    <div class="details-item">
      <label>IME:</label>
      <span>{{data.ime}}</span>
    </div>
    <div class="details-item">
      <label>PREZIME:</label>
      <span>{{data.prezime}}</span>
    </div>
    <div class="details-item">
      <label>IZNOS:</label>
      <span>{{data.iznos}}</span>
    </div>
    <div class="details-item">
      <label>MJESEC:</label>
      <span>{{data.mjesec}}</span>
    </div>
  </div>
</div>
{% endblock %}

app/templates/pages/zaposlenik_placa/zaposlenik_placa_all.html
{% extends "index.html" %}{% import
'components/nav-cards/zaposlenik_placa_nav_card.html' as nav_card %} {% block
content %} {{ nav_card.zaposlenik_placa_nav_card() }}
<div class="card">
  <table>
    <thead>
      <tr>
        <th>Ime</th>
        <th>Prezime</th>
        <th>Iznos plaće</th>
        <th>Mjesec</th>
        <th>Restoran</th>
      </tr>
    </thead>
    <tbody>
      {% for datapoint in data %}
      <tr>
        <td>{{ datapoint.ime }}</td>
        <td>{{ datapoint.prezime }}</td>
        <td>{{ datapoint.placa }}</td>
        <td>{{ datapoint.mjesec }}</td>
        <td>{{ datapoint.restoran }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/pages/zaposlenik_placa/zaposlenik_placa_create.html
{% extends "index.html" %} {% block content %}
<h2>Plati zaposlenicima plaću:</h2>
<div class="card">
  <a href="{{url_for('zaposlenik_placa_routes.get_zaposlenik_place_months')}}"
    >Odustani</a
  >
</div>
<div class="card">
  <form
    class="create-form"
    action="{{url_for('zaposlenik_placa_routes.created_zaposlenik_place')}}"
    method="POST"
    enctype="multipart/form-data"
  >
    <div class="form-input-group">
      <label for="mjesec">Mjesec:</label>
      <input type="month" name="mjesec" id="mjesec" required />
    </div>
    <div class="form-input-group">
      <label>Zaposlenici:</label>
    </div>
    {% for datapoint in data %}
    <div class="form-input-group">
      <label for="iznos_place"
        >{{ datapoint.ime }} {{ datapoint.prezime }}:</label
      >
      <input
        type="number"
        step="0.01"
        name="iznos_place_{{ datapoint.id }}"
        id="iznos_place"
        value="{{ datapoint.iznos_place }}"
      />
    </div>
    {% endfor %}
    <div class="form-input-group">
      <span></span>
      <input type="submit" value="Plati zaposlenike" />
    </div>
  </form>
</div>
{% endblock %}

app/templates/pages/zaposlenik_placa/zaposlenik_place.html
{% import 'components/buttons/add_item_button.html' as add_item_button %} {%
import 'components/buttons/view_item_button.html' as view_item_button %} {%
import 'components/buttons/delete_item_button.html' as delete_item_button %} {%
extends "index.html" %}{% import
'components/nav-cards/zaposlenik_placa_nav_card.html' as nav_card %} {% block
content %} {{ nav_card.zaposlenik_placa_nav_card() }}
<div class="card">
  {{
  add_item_button.add_item_button_link('zaposlenik_placa_routes.create_zaposlenik_place',
  'Plati zaposlenicima plaću') }}
</div>
<div class="card">
  <table>
    <thead>
      <tr>
        <th>Mjesec</th>
        <th>Iznos</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for datapoint in data %}
      <tr>
        <td>{{ datapoint.mjesec }}</td>
        <td>{{ datapoint.iznos }}</td>
        <td class="button-cell">
          <div class="button-group">
            <a
              href="{{ url_for('zaposlenik_placa_routes.get_zaposlenik_place_by_month', mjesec=datapoint.mjesec) }}"
              >Pregledaj</a
            >
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/pages/zaposlenik_placa/zaposlenik_place_month.html
{%import 'components/buttons/view_item_button.html' as view_item_button %} {%
import 'components/buttons/delete_item_button.html' as delete_item_button %} {%
extends "index.html" %} {% block content %}
<div class="card">
  <table>
    <thead>
      <tr>
        <th>Ime</th>
        <th>Prezime</th>
        <th>Iznos</th>
        <th>Mjesec</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for datapoint in data %}
      <tr>
        <td>{{ datapoint.ime }}</td>
        <td>{{ datapoint.prezime }}</td>
        <td>{{ datapoint.iznos }}</td>
        <td>{{ datapoint.mjesec }}</td>
        <td class="button-cell">
          <div class="button-group">
            {{
            view_item_button.view_item_button_link('zaposlenik_placa_routes.get_zaposlenik_placa',
            datapoint.id, 'Pregledaj') }}
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}