app/routes/narudzba_routes.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for
from app.router.routes import NarudzbaRoutesEnum
from app.services.narudzba_service import NarudzbaService
from app.services.skladiste_service import SkladisteService
from app.services.sastojak_service import SastojakService
from app.interfaces.iroutes import IRoutes

class NarudzbaRoutes(IRoutes):
    def __init__(self, app: Flask):
        self.app = app
        self.narudzba_routes_bp = Blueprint('narudzba_routes', __name__)
        self.narudzba_service = NarudzbaService(self.app)
        self.skladiste_service = SkladisteService(self.app)
        self.sastojak_service = SastojakService(self.app)
        self.statusi = ['ZAVRSENO', 'PONISTENO', 'NERIJESENO']
        
    def register_routes(self):
        self.app.logger.info("Registering routes for Narudzba")
        self.app.logger.info(f"Registering route: {NarudzbaRoutesEnum.NARUDZBA.value}")
        self.narudzba_routes_bp.route(NarudzbaRoutesEnum.NARUDZBA.value, methods=["GET"])(self.get_narudzbe)
        self.app.logger.info(f"Registering route: {NarudzbaRoutesEnum.NARUDZBA_ID.value}")
        self.narudzba_routes_bp.route(NarudzbaRoutesEnum.NARUDZBA_ID.value, methods=["GET"])(self.get_narudzba)
        self.app.logger.info(f"Registering route: {NarudzbaRoutesEnum.NARUDZBA_CREATE.value}")
        self.narudzba_routes_bp.route(NarudzbaRoutesEnum.NARUDZBA_CREATE.value, methods=["GET"])(self.create_narudzba)
        self.app.logger.info(f"Registering route: {NarudzbaRoutesEnum.NARUDZBA_CREATED.value}")
        self.narudzba_routes_bp.route(NarudzbaRoutesEnum.NARUDZBA_CREATED.value, methods=["POST"])(self.created_narudzba)
        self.app.logger.info(f"Registering route: {NarudzbaRoutesEnum.NARUDZBA_UPDATE.value}")
        self.narudzba_routes_bp.route(NarudzbaRoutesEnum.NARUDZBA_UPDATE.value, methods=["GET"])(self.update_narudzba)
        self.app.logger.info(f"Registering route: {NarudzbaRoutesEnum.NARUDZBA_UPDATED.value}")
        self.narudzba_routes_bp.route(NarudzbaRoutesEnum.NARUDZBA_UPDATED.value, methods=["POST"])(self.updated_narudzba)
        self.app.logger.info(f"Registering route: {NarudzbaRoutesEnum.NARUDZBA_DELETE.value}")
        self.narudzba_routes_bp.route(NarudzbaRoutesEnum.NARUDZBA_DELETE.value, methods=["POST"])(self.delete_narudzba)
        self.app.logger.info(f"Registering route: {NarudzbaRoutesEnum.NARUDZBA_FINISH.value}")
        self.narudzba_routes_bp.route(NarudzbaRoutesEnum.NARUDZBA_FINISH.value, methods=["POST"])(self.finish_narudzba)
        self.app.register_blueprint(self.narudzba_routes_bp)
        
    def get_narudzbe(self):
        try:
            data = self.narudzba_service.get_narudzbe()
            return render_template(self.app.router.get_template(NarudzbaRoutesEnum.NARUDZBA.value), data=data)
        except Exception as e:
            self.app.logger.error(f"Error in get_narudzbe: {e}")
            return "Internal Server Error", 500
        
    def get_narudzba(self, id):
        try:
            data = self.narudzba_service.get_narudzba(id)
            sastojci = self.sastojak_service.get_sastojak_by_narudzba(id)
            return render_template(self.app.router.get_template(NarudzbaRoutesEnum.NARUDZBA_ID.value), data=data, sastojci=sastojci)
        except Exception as e:
            self.app.logger.error(f"Error in get_narudzba: {e}")
            return "Internal Server Error", 500
        
    def create_narudzba(self):
        try:
            skladista = self.skladiste_service.get_skladista()
            sastojci = self.sastojak_service.get_sastojci()
            return render_template(self.app.router.get_template(NarudzbaRoutesEnum.NARUDZBA_CREATE.value), skladista=skladista, sastojci=sastojci)
        except Exception as e:
            self.app.logger.error(f"Error in create_narudzba: {e}")
            return "Internal Server Error", 500
        
    def created_narudzba(self):
        try:
            form = request.form
            narudzba = {
                'skladiste_id': form['skladiste_id'],
                'naziv': form['naziv']
            }
            
            sastojci = []
            for key in form.keys():
                if "sastojak" in key:
                    sastojak = {
                        'id': key.split("_")[1],
                        'kolicina': form[key]
                    }
                    sastojci.append(sastojak)
                    
            self.narudzba_service.insert_narudzbe_sastojci(narudzba, sastojci)
            return redirect(url_for('narudzba_routes.get_narudzbe'))
        except Exception as e:
            self.app.logger.error(f"Error in created_narudzba: {e}")
            return "Internal Server Error", 500
        
    def update_narudzba(self, id):
        try:
            data = self.narudzba_service.get_narudzba(id)
            skladista = self.skladiste_service.get_skladista()
            sastojci = self.sastojak_service.get_sastojak_by_skladiste(data['skladiste_id'])
            sastojci_narudzbe = self.sastojak_service.get_sastojak_by_narudzba(id)
            return render_template(self.app.router.get_template(NarudzbaRoutesEnum.NARUDZBA_UPDATE.value), data=data, skladista=skladista, sastojci=sastojci, sastojci_narudzbe=sastojci_narudzbe)
        except Exception as e:
            self.app.logger.error(f"Error in update_narudzba: {e}")
            return "Internal Server Error", 500
        
    def updated_narudzba(self, id):
        try:
            form = request.form
            narudzba = {
                'skladiste_id': form['skladiste_id'],
                'naziv': form['naziv']
            }
            
            sastojci_updated = []
            for key, value in form.items():
                if key.startswith('sastojak_') and int(value) > 0:
                    sastojak_id = key.split('_')[1]
                    kolicina = value
                    sastojci_updated.append({
                        'sastojak_id': sastojak_id,
                        'kolicina': kolicina
                    })
                    
            sastojci = self.sastojak_service.get_sastojak_by_narudzba(id)
            self.narudzba_service.update_narudzbe_sastojci(id, narudzba, sastojci, sastojci_updated)
            return redirect(url_for('narudzba_routes.get_narudzba', id=id))
        except Exception as e:
            self.app.logger.error(f"Error in updated_narudzba: {e}")
            return "Internal Server Error", 500
        
    def delete_narudzba(self, id):
        try:
            self.narudzba_service.delete_narudzba(id)
            return redirect(url_for('narudzba_routes.get_narudzbe'))
        except Exception as e:
            self.app.logger.error(f"Error in delete_narudzba: {e}")
            return "Internal Server Error", 500
        
    def finish_narudzba(self, id):
        try:
            self.narudzba_service.finish_narudzba(id)
            self.narudzba_service.process_narudzba_transaction(id)
            return redirect(url_for('narudzba_routes.get_narudzbe'))
        except Exception as e:
            self.app.logger.error(f"Error in finish_narudzba: {e}")
            return "Internal Server Error", 500

app/templates/pages/narudzba/narudzba.html
{% extends "index.html" %} {% block content %} {% import
'components/buttons/delete_item_button.html' as delete_item_button %} {% import
'components/buttons/view_item_button.html' as view_item_button %}
<h2>Detalji narudžbe:</h2>
{% import 'components/buttons/update_item_button.html' as update_item_button
%}{% if data.status_narudzbe == "NERIJESENO" %}
<div class="single-item-buttons card">
  {{
  delete_item_button.delete_item_button_form('narudzba_routes.delete_narudzba',
  data.id, 'Obriši narudžbu') }} {{
  update_item_button.update_item_button_link('narudzba_routes.update_narudzba',
  data.id, 'Ažuriraj narudžbu') }}
</div>
{% endif %}
<div class="card">
  <div class="single-item-details">
    <div class="details-item">
      <label>ID:</label>
      <span>{{data.id}}</span>
    </div>
    <div class="details-item">
      <label>SKLADIŠTE:</label>
      <span>{{data.naziv_restoran}}: {{data.skladiste_id}}</span>
    </div>
    <div class="details-item">
      <label>NAZIV:</label>
      <span>{{data.naziv}}</span>
    </div>
    <div class="details-item">
      <label>STATUS:</label>
      <span>{{data.status_narudzbe}}</span>
    </div>
  </div>
</div>
<h3>Sastojci:</h3>
<div class="card">
  <table>
    <thead>
      <tr>
        <th></th>
        <th>Naziv</th>
        <th>Cijena</th>
        <th>Količina</th>
        <th>Tip količine</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for sastojak in sastojci %}
      <tr>
        <td class="image-cell">
          <div class="table-image-wrapper">
            <img
              src="data:image/jpeg;base64,{{ sastojak.slika }}"
              alt="Sastojak Slika"
              width="25"
              height="25"
            />
          </div>
        </td>
        <td>{{ sastojak.naziv }}</td>
        <td>{{ sastojak.cijena }}</td>
        <td>{{ sastojak.kolicina }}</td>
        <td>{{ sastojak.kolicina_tip }}</td>
        <td class="button-cell">
          <div class="button-group">
            {{
            view_item_button.view_item_button_link('sastojak_routes.get_sastojak',
            sastojak.id, 'Pregledaj') }}
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/pages/narudzba/narudzba_create.html
{% extends "index.html" %} {% block content %}
<h2>Dodaj narudžbu:</h2>
<div class="card">
  <a href="{{url_for('narudzba_routes.get_narudzbe')}}">Odustani</a>
</div>
<div class="card">
  <form
    class="create-form"
    action="{{url_for('narudzba_routes.created_narudzba')}}"
    method="POST"
    enctype="multipart/form-data"
  >
    <div class="form-input-group">
      <label for="skladiste_id">Skladište:</label>
      <select
        name="skladiste_id"
        id="skladiste_id"
        required
        {%
        if
        skladista|length
      >
        0 %} value="{{skladista[0].id}}" {% endif %} > {% for skladiste in
        skladista %}
        <option value="{{skladiste.id}}">
          {{skladiste.naziv}}: {{skladiste.id}}
        </option>
        {% endfor %}
      </select>
    </div>
    <div class="form-input-group">
      <label for="naziv">Naziv:</label>
      <input type="text" name="naziv" id="naziv" required />
    </div>
    <h3>Sastojci:</h3>
    {% for sastojak in sastojci %}
    <div class="form-input-group sastojak-input">
      <label for="sastojak_{{sastojak.id}}">{{sastojak.naziv}}</label>
      <input
        type="number"
        step="1"
        name="sastojak_{{sastojak.id}}"
        id="sastojak_{{sastojak.id}}"
        value="{{sastojak.potrebna_kolicina - sastojak.trenutna_kolicina if sastojak.potrebna_kolicina - sastojak.trenutna_kolicina > 0 else 0}}"
        required
      />
      <span
        >{{sastojak.trenutna_kolicina}} / {{sastojak.potrebna_kolicina}} {{
        sastojak.kolicina_tip }}
      </span>
    </div>
    {% endfor %}
    <div class="form-input-group">
      <span></span>
      <input type="submit" value="Dodaj narudžbu" />
    </div>
  </form>
</div>
{% endblock %}

app/templates/pages/narudzba/narudzba_update.html
{% extends "index.html" %} {% import 'components/buttons/view_item_button.html'
as view_item_button %} {% block content %}
<h2>Ažuriraj narudžbu:</h2>
<div class="single-item-buttons card">
  {{ view_item_button.view_item_button_link('narudzba_routes.get_narudzba',
  data.id, 'Odustani') }}
</div>
<div class="card">
  <form
    class="update-form"
    action="{{url_for('narudzba_routes.updated_narudzba', id=data.id)}}"
    method="POST"
    enctype="multipart/form-data"
  >
    <div class="form-input-group">
      <label for="skladiste_id">Restoran:</label>
      <select name="skladiste_id" id="skladiste_id" required>
        {% for skladiste in skladista %}
        <option value="{{skladiste.id}}" {% if skladiste.id == data.skladiste_id %} selected {% endif %}>{{skladiste.naziv}}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-input-group">
      <label for="naziv">Naziv:</label>
      <input
        type="text"
        name="naziv"
        id="naziv"
        required
        value="{{ data.naziv }}"
      />
    </div>
    <h3>Sastojci:</h3>
    {% for sastojak in sastojci %}
    <div class="form-input-group sastojak-input">
      <label for="sastojak_{{sastojak.id}}">{{sastojak.naziv}}</label>
      <input type="number" step="1" {% set sastojak_narudzbe =
      sastojci_narudzbe|selectattr('id', 'equalto', sastojak.id)|first %}
      value="{{ sastojak_narudzbe.kolicina if sastojak_narudzbe else 0 }}"
      name="sastojak_{{sastojak.id}}" id="sastojak_{{sastojak.id}}" required />
      <span> {{sastojak.trenutna_kolicina}} / {{sastojak.potrebna_kolicina}} {{
        sastojak.kolicina_tip }} </span>
    </div>
    {% endfor %}
    <div class="form-input-group">
      <span></span>
      <input type="submit" value="Ažuriraj narudžbu" />
    </div>
  </form>
</div>
{% endblock %}

app/templates/pages/narudzba/narudzbe.html
{% import 'components/buttons/add_item_button.html' as add_item_button %} {%
import 'components/buttons/view_item_button.html' as view_item_button %} {%
import 'components/buttons/delete_item_button.html' as delete_item_button %} {%
extends "index.html" %} {% block content %}
<div class="card">
  {{ add_item_button.add_item_button_link('narudzba_routes.create_narudzba',
  'Dodaj narudžbu') }}
</div>
<div class="card">
  <table>
    <thead>
      <tr>
        <th>Skladište</th>
        <th>Naziv</th>
        <th>Status</th>
        <th>Ukupna cijena</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for datapoint in data %}
      <tr>
        <td>{{ datapoint.naziv_restoran }}: {{ datapoint.skladiste_id }}</td>
        <td>{{ datapoint.naziv }}</td>
        <td>{{ datapoint.status_narudzbe }}</td>
        <td>{{ datapoint.ukupna_cijena }}</td>
        <td class="button-cell">
          <div class="button-group">
            {{
            view_item_button.view_item_button_link('narudzba_routes.get_narudzba',
            datapoint.id, 'Pregledaj') }} {% if datapoint.status_narudzbe ==
            "NERIJESENO" %} {{
            delete_item_button.delete_item_button_form('narudzba_routes.delete_narudzba',
            datapoint.id, 'Obriši narudžbu') }}
            <form
              action="{{url_for('narudzba_routes.finish_narudzba', id=datapoint.id)}}"
              method="POST"
            >
              <input type="submit" value="Završi narudžbu" />
            </form>
            {% endif %}
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}