app/routes/skladiste_routes.py
from app.interfaces.iroutes import IRoutes
from flask import Blueprint, Flask, request, redirect, url_for, render_template
from app.services.skladiste_service import SkladisteService
from app.services.restoran_service import RestoranService
from app.router.routes import SkladisteRoutesEnum

class SkladisteRoutes(IRoutes):
    def __init__(self, app: Flask):
        self.app = app
        self.skladiste_routes_bp = Blueprint('skladiste_routes', __name__)
        self.skladiste_service = SkladisteService(self.app)
        self.restoran_service = RestoranService(self.app)
        
    def register_routes(self):
        self.app.logger.info("Registering routes for Skladiste")
        self.app.logger.info(f"Registering route: {SkladisteRoutesEnum.SKLADISTE.value}")
        self.skladiste_routes_bp.route(SkladisteRoutesEnum.SKLADISTE.value, methods=["GET"])(self.get_skladista)
        self.app.logger.info(f"Registering route: {SkladisteRoutesEnum.SKLADISTE_ID.value}")
        self.skladiste_routes_bp.route(SkladisteRoutesEnum.SKLADISTE_ID.value, methods=["GET"])(self.get_skladiste)
        self.app.logger.info(f"Registering route: {SkladisteRoutesEnum.SKLADISTE_CREATE.value}")
        self.skladiste_routes_bp.route(SkladisteRoutesEnum.SKLADISTE_CREATE.value, methods=["GET"])(self.create_skladiste)
        self.app.logger.info(f"Registering route: {SkladisteRoutesEnum.SKLADISTE_CREATED.value}")
        self.skladiste_routes_bp.route(SkladisteRoutesEnum.SKLADISTE_CREATED.value, methods=["POST"])(self.created_skladiste)
        self.app.logger.info(f"Registering route: {SkladisteRoutesEnum.SKLADISTE_UPDATE.value}")
        self.skladiste_routes_bp.route(SkladisteRoutesEnum.SKLADISTE_UPDATE.value, methods=["GET"])(self.update_skladiste)
        self.app.logger.info(f"Registering route: {SkladisteRoutesEnum.SKLADISTE_UPDATED.value}")
        self.skladiste_routes_bp.route(SkladisteRoutesEnum.SKLADISTE_UPDATED.value, methods=["POST"])(self.updated_skladiste)
        self.app.logger.info(f"Registering route: {SkladisteRoutesEnum.SKLADISTE_DELETE.value}")
        self.skladiste_routes_bp.route(SkladisteRoutesEnum.SKLADISTE_DELETE.value, methods=["POST"])(self.delete_skladiste)
        self.app.register_blueprint(self.skladiste_routes_bp)
        
    def get_skladista(self):
        try:
            data = self.skladiste_service.get_skladista()
            return render_template(self.app.router.get_template(SkladisteRoutesEnum.SKLADISTE.value), data=data)
        except Exception as e:
            self.app.logger.error(f"Error in get_skladista: {e}")
            return "Internal Server Error", 500
        
    def get_skladiste(self, id):
        try:
            data = self.skladiste_service.get_skladiste(id)
            return render_template(self.app.router.get_template(SkladisteRoutesEnum.SKLADISTE_ID.value), data=data)
        except Exception as e:
            self.app.logger.error(f"Error in get_skladiste: {e}")
            return "Internal Server Error", 500
        
    def create_skladiste(self):
        try:
            data = self.restoran_service.get_restorani()
            return render_template(self.app.router.get_template(SkladisteRoutesEnum.SKLADISTE_CREATE.value), data=data)
        except Exception as e:
            self.app.logger.error(f"Error in create_skladiste: {e}")
            return "Internal Server Error", 500
        
    def created_skladiste(self):
        try:
            form = request.form
            skladiste = {
                'restoran_id': form['restoran_id'],
            }
            
            self.skladiste_service.insert_skladiste(skladiste)
            return redirect(url_for('skladiste_routes.get_skladista'))
        except Exception as e:
            self.app.logger.error(f"Error in created_skladiste: {e}")
            return "Internal Server Error", 500
        
    def update_skladiste(self, id):
        try:
            data = self.skladiste_service.get_skladiste(id)
            restorani = self.restoran_service.get_restorani()
            return render_template(self.app.router.get_template(SkladisteRoutesEnum.SKLADISTE_UPDATE.value), data=data, restorani=restorani)
        except Exception as e:
            self.app.logger.error(f"Error in update_skladiste: {e}")
            return "Internal Server Error", 500
        
    def updated_skladiste(self, id):
        try:
            form = request.form
            skladiste = {
                'restoran_id': form['restoran_id'],
            }
            self.skladiste_service.update_skladiste(skladiste, id)
            return redirect(url_for('skladiste_routes.get_skladiste', id=id))
        except Exception as e:
            self.app.logger.error(f"Error in updated_skladiste: {e}")
            return "Internal Server Error", 500
        
    def delete_skladiste(self, id):
        try:
            self.skladiste_service.delete_skladiste(id)
            return redirect(url_for('skladiste_routes.get_skladista'))
        except Exception as e:
            self.app.logger.error(f"Error in delete_skladiste: {e}")
            return "Internal Server Error", 500

app/templates/pages/skladiste/skladista.html
{% import 'components/buttons/add_item_button.html' as add_item_button %} {%
import 'components/buttons/view_item_button.html' as view_item_button %} {%
import 'components/buttons/delete_item_button.html' as delete_item_button %} {%
extends "index.html" %} {% block content %}
<div class="card">
  {{ add_item_button.add_item_button_link('skladiste_routes.create_skladiste',
  'Dodaj skladište') }}
</div>
<div class="card">
  <table>
    <thead>
      <tr>
        <th>Naziv restorana</th>
        <th>Stanje</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for datapoint in data %}
      <tr>
        <td>{{ datapoint.naziv }}</td>
        <td>{{ datapoint.stanje }}</td>
        <td class="button-cell">
          <div class="button-group">
            {{
            view_item_button.view_item_button_link('skladiste_routes.get_skladiste',
            datapoint.id, 'Pregledaj') }} {{
            delete_item_button.delete_item_button_form('skladiste_routes.delete_skladiste',
            datapoint.id, 'Obriši') }}
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/pages/skladiste/skladiste.html
{% extends "index.html" %} {% block content %} {% import
'components/buttons/delete_item_button.html' as delete_item_button %}
<h2>Detalji skladista:</h2>
<div class="single-item-buttons card">
  {% import 'components/buttons/update_item_button.html' as update_item_button
  %} {{
  delete_item_button.delete_item_button_form('skladiste_routes.delete_skladiste',
  data.id, 'Obriši skladište') }} {{
  update_item_button.update_item_button_link('skladiste_routes.update_skladiste',
  data.id, 'Ažuriraj skladište') }}
</div>
<div class="card">
  <div class="single-item-details">
    <div class="details-item">
      <label>ID:</label>
      <span>{{data.id}}</span>
    </div>
    <div class="details-item">
      <label>NAZIV RESTORANA:</label>
      <span>{{data.naziv}}</span>
    </div>
    <div class="details-item">
      <label>STANJE:</label>
      <span>{{data.stanje}}</span>
    </div>
  </div>
</div>
{% endblock %}

app/templates/pages/skladiste/skladiste_create.html
{% extends "index.html" %} {% block content %}
<h2>Dodaj skladište:</h2>
<div class="card">
  <a href="{{url_for('skladiste_routes.get_skladista')}}">Odustani</a>
</div>
<div class="card">
  <form
    class="create-form"
    action="{{url_for('skladiste_routes.created_skladiste')}}"
    method="POST"
    enctype="multipart/form-data"
  >
    <div class="form-input-group">
      <label for="restoran_id">Restoran:</label>
      <select name="restoran_id" id="restoran_id" required {% if data|length>
        0 %} value="{{data[0].id}}" {% endif %} > {% for datapoint in data %}
        <option value="{{datapoint.id}}">{{datapoint.naziv}}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-input-group">
      <span></span>
      <input type="submit" value="Dodaj skladište" />
    </div>
  </form>
</div>
{% endblock %}

app/templates/pages/skladiste/skladiste_update.html
{% extends "index.html" %} {% import 'components/buttons/view_item_button.html'
as view_item_button %} {% block content %}
<h2>Ažuriraj skladište:</h2>
<div class="single-item-buttons card">
  {{ view_item_button.view_item_button_link('skladiste_routes.get_skladiste',
  data.id, 'Odustani') }}
</div>
<div class="card">
  <form
    class="update-form"
    action="{{url_for('skladiste_routes.updated_skladiste', id=data.id)}}"
    method="POST"
    enctype="multipart/form-data"
  >
    <div class="form-input-group">
      <label for="restoran_id">Restoran:</label>
      <select
        name="restoran_id"
        id="restoran_id"
        required
        value="{{
        data.restoran_id}}"
      >
        {% for restoran in restorani %}
        <option value="{{restoran.id}}">{{restoran.naziv}}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-input-group">
      <span></span>
      <input type="submit" value="Ažuriraj skladište" />
    </div>
  </form>
</div>
{% endblock %}