app/routes/rezervacija_routes.py
from flask import Flask, Blueprint, request, redirect, render_template, url_for
from app.interfaces.iroutes import IRoutes
from app.services.rezervacija_service import RezervacijaService
from app.services.restoran_service import RestoranService
from app.services.stol_service import StolService
from app.router.routes import RezervacijaRoutesEnum

class RezervacijaRoutes(IRoutes):
    def __init__(self, app: Flask):
        self.app = app
        self.rezervacija_service = RezervacijaService(self.app)
        self.restoran_service = RestoranService(self.app)
        self.stol_service = StolService(self.app)
        self.rezervacija_routes_bp = Blueprint('rezervacija_routes', __name__)
        
    def register_routes(self):
        self.app.logger.info("Registering routes for Rezervacija")
        self.app.logger.info(f"Registering route: {RezervacijaRoutesEnum.REZERVACIJA.value}")
        self.rezervacija_routes_bp.route(RezervacijaRoutesEnum.REZERVACIJA.value, methods=["GET"])(self.get_rezervacije)
        self.app.logger.info(f"Registering route: {RezervacijaRoutesEnum.REZERVACIJA_ID.value}")
        self.rezervacija_routes_bp.route(RezervacijaRoutesEnum.REZERVACIJA_ID.value, methods=["GET"])(self.get_rezervacija)
        self.app.logger.info(f"Registering route: {RezervacijaRoutesEnum.REZERVACIJA_CREATE.value}")
        self.rezervacija_routes_bp.route(RezervacijaRoutesEnum.REZERVACIJA_CREATE.value, methods=["GET"])(self.create_rezervacija)
        self.app.logger.info(f"Registering route: {RezervacijaRoutesEnum.REZERVACIJA_CREATED.value}")
        self.rezervacija_routes_bp.route(RezervacijaRoutesEnum.REZERVACIJA_CREATED.value, methods=["POST"])(self.created_rezervacija)
        self.app.logger.info(f"Registering route: {RezervacijaRoutesEnum.REZERVACIJA_UPDATE.value}")
        self.rezervacija_routes_bp.route(RezervacijaRoutesEnum.REZERVACIJA_UPDATE.value, methods=["GET"])(self.update_rezervacija)
        self.app.logger.info(f"Registering route: {RezervacijaRoutesEnum.REZERVACIJA_UPDATED.value}")
        self.rezervacija_routes_bp.route(RezervacijaRoutesEnum.REZERVACIJA_UPDATED.value, methods=["POST"])(self.updated_rezervacija)
        self.app.logger.info(f"Registering route: {RezervacijaRoutesEnum.REZERVACIJA_DELETE.value}")
        self.rezervacija_routes_bp.route(RezervacijaRoutesEnum.REZERVACIJA_DELETE.value, methods=["POST"])(self.delete_rezervacija)
        self.app.logger.info(f"Registering route: {RezervacijaRoutesEnum.REZERVACIJA_BY_LOCATION_WITH_COUNT.value}")
        self.rezervacija_routes_bp.route(RezervacijaRoutesEnum.REZERVACIJA_BY_LOCATION_WITH_COUNT.value, methods=["GET"])(self.get_rezervacija_by_location_with_count)
        self.app.logger.info(f"Registering route: {RezervacijaRoutesEnum.REZERVACIJA_WITH_STOL_DATA.value}")
        self.rezervacija_routes_bp.route(RezervacijaRoutesEnum.REZERVACIJA_WITH_STOL_DATA.value, methods=["GET"])(self.get_rezervacija_with_stol_data)
        self.app.logger.info(f"Registering route: {RezervacijaRoutesEnum.REZERVACIJA_COUNT_BY_STOL_LOCATION.value}")
        self.rezervacija_routes_bp.route(RezervacijaRoutesEnum.REZERVACIJA_COUNT_BY_STOL_LOCATION.value, methods=["GET"])(self.get_rezervacija_count_by_stol_location)
        self.app.logger.info(f"Registering route: {RezervacijaRoutesEnum.REZERVACIJA_ACTIVE_WITH_STOL_DATA.value}")
        self.rezervacija_routes_bp.route(RezervacijaRoutesEnum.REZERVACIJA_ACTIVE_WITH_STOL_DATA.value, methods=["GET"])(self.get_active_rezervacija_with_stol_data)
        self.app.register_blueprint(self.rezervacija_routes_bp)
        
    def get_rezervacije(self):
        try:
            data = self.rezervacija_service.get_rezervacije()
            return render_template(self.app.router.get_template(RezervacijaRoutesEnum.REZERVACIJA.value), data=data)
        except Exception as e:
            self.app.logger.error(f"Error in get_rezervacije: {e}")
            return "Internal Server Error", 500
        
    def get_rezervacija(self, id):
        try:
            data = self.rezervacija_service.get_rezervacija(id)
            return render_template(self.app.router.get_template(RezervacijaRoutesEnum.REZERVACIJA_ID.value), data=data)
        except Exception as e:
            self.app.logger.error(f"Error in get_rezervacija: {e}")
            return "Internal Server Error", 500
        
    def create_rezervacija(self):
        try:
            message = request.args.get('message') 
            restorani = self.restoran_service.get_restorani()
            stolovi = self.stol_service.get_stolovi()
            
            restoran_id = request.args.get('restoran_id')
            broj_mjesta = request.args.get('broj_mjesta')
            lokacija = request.args.get('lokacija')
            
            appropritate_stol_id = None
            if restoran_id and broj_mjesta and lokacija:
                appropritate_stol_id = self.stol_service.get_appropriate_stol(restoran_id, broj_mjesta, lokacija)
            
            return render_template(self.app.router.get_template(RezervacijaRoutesEnum.REZERVACIJA_CREATE.value), restorani=restorani, stolovi=stolovi, message=message, appropritate_stol_id=appropritate_stol_id)
        except Exception as e:
            self.app.logger.error(f"Error in create_rezervacija: {e}")
            return "Internal Server Error", 500
        
    def created_rezervacija(self):
        try:
            form = request.form
            rezervacija = {
                "restoran_id": form['restoran_id'],
                "stol_id": form['stol_id'],
                "ime": form['ime'],
                "vrijeme": form['vrijeme'],
                "broj_osoba": form['broj_osoba'],
            }
            
            is_avilable = self.stol_service.check_stol_is_avilable(rezervacija['stol_id'], rezervacija['vrijeme'])
            
            if is_avilable == 0:
                return redirect(url_for('rezervacija_routes.create_rezervacija', message="Stol is not avilable"))
            
            self.rezervacija_service.insert_rezervacija(rezervacija)
            return redirect(url_for('rezervacija_routes.get_rezervacije'))
        except Exception as e:
            self.app.logger.error(f"Error in created_rezervacija: {e}")
            return "Internal Server Error", 500
        
    def update_rezervacija(self, id):
        try:
            data = self.rezervacija_service.get_rezervacija(id)
            restorani = self.restoran_service.get_restorani()
            stolovi = self.stol_service.get_stolovi()
            return render_template(self.app.router.get_template(RezervacijaRoutesEnum.REZERVACIJA_UPDATE.value), data=data, restorani=restorani, stolovi=stolovi)
        except Exception as e:
            self.app.logger.error(f"Error in update_rezervacija: {e}")
            return "Internal Server Error", 500
        
    def updated_rezervacija(self, id):
        try:
            form = request.form
            rezervacija = {
                "restoran_id": form['restoran_id'],
                "stol_id": form['stol_id'],
                "ime": form['ime'],
                "vrijeme": form['vrijeme'],
                "broj_osoba": form['broj_osoba'],
            }
            self.rezervacija_service.update_rezervacija(rezervacija, id)
            return redirect(url_for('rezervacija_routes.get_rezervacija', id=id))
        except Exception as e:
            self.app.logger.error(f"Error in updated_rezervacija: {e}")
            return "Internal Server Error", 500
        
    def delete_rezervacija(self, id):
        try:
            self.rezervacija_service.delete_rezervacija(id)
            return redirect(url_for('rezervacija_routes.get_rezervacije'))
        except Exception as e:
            self.app.logger.error(f"Error in delete_rezervacija: {e}")
            return "Internal Server Error", 500
        
    def get_rezervacija_by_location_with_count(self):
        try:
            data = self.rezervacija_service.get_rezervacija_by_location_with_count()
            return render_template(self.app.router.get_template(RezervacijaRoutesEnum.REZERVACIJA_BY_LOCATION_WITH_COUNT.value), data=data)
        except Exception as e:
            self.app.logger.error(f"Error in get_rezervacija_by_location_with_count: {e}")
            return "Internal Server Error", 500
        
    def get_rezervacija_with_stol_data(self):
        try:
            data = self.rezervacija_service.get_rezervacija_with_stol_data()
            return render_template(self.app.router.get_template(RezervacijaRoutesEnum.REZERVACIJA_WITH_STOL_DATA.value), data=data)
        except Exception as e:
            self.app.logger.error(f"Error in get_rezervacija_with_stol_data: {e}")
            return "Internal Server Error", 500
        
    def get_rezervacija_count_by_stol_location(self):
        try:
            data = self.rezervacija_service.get_rezervacija_count_by_stol_location()
            return render_template(self.app.router.get_template(RezervacijaRoutesEnum.REZERVACIJA_COUNT_BY_STOL_LOCATION.value), data=data)
        except Exception as e:
            self.app.logger.error(f"Error in get_rezervacija_count_by_stol_location: {e}")
            return "Internal Server Error", 500
        
    def get_active_rezervacija_with_stol_data(self):
        try:
            data = self.rezervacija_service.get_active_rezervacija_with_stol_data()
            return render_template(self.app.router.get_template(RezervacijaRoutesEnum.REZERVACIJA_ACTIVE_WITH_STOL_DATA.value), data=data)
        except Exception as e:
            self.app.logger.error(f"Error in get_active_rezervacija_with_stol_data: {e}")
            return "Internal Server Error", 500

app/templates/pages/rezervacija/rezervacija.html
{% extends "index.html" %} {% block content %} {% import
'components/buttons/delete_item_button.html' as delete_item_button %}
<h2>Detalji rezervacija:</h2>
<div class="single-item-buttons card">
  {% import 'components/buttons/update_item_button.html' as update_item_button
  %} {{
  delete_item_button.delete_item_button_form('rezervacija_routes.delete_rezervacija',
  data.id, 'Obriši rezervaciju') }} {{
  update_item_button.update_item_button_link('rezervacija_routes.update_rezervacija',
  data.id, 'Ažuriraj rezervaciju') }}
</div>
<div class="card">
  <div class="single-item-details">
    <div class="details-item">
      <label>ID:</label>
      <span>{{data.id}}</span>
    </div>
    <div class="details-item">
      <label>NAZIV RESTORANA:</label>
      <span>{{data.naziv_restoran}}</span>
    </div>
    <div class="details-item">
      <label>BROJ STOLA:</label>
      <span>{{data.broj_stola}}</span>
    </div>
    <div class="details-item">
      <label>BROJ MJESTA STOLA:</label>
      <span>{{data.broj_mjesta_stola}}</span>
    </div>
    <div class="details-item">
      <label>IME:</label>
      <span>{{data.ime}}</span>
    </div>
    <div class="details-item">
      <label>VRIJEME:</label>
      <span>{{data.vrijeme}}</span>
    </div>
    <div class="details-item">
      <label>BROJ OSOBA:</label>
      <span>{{data.broj_osoba}}</span>
    </div>
  </div>
</div>
{% endblock %}

app/templates/pages/rezervacija/rezervacija_active_with_stol_data.html
{% extends "index.html" %} {% import
'components/nav-cards/rezervacija_nav_card.html' as nav_card %} {% block content
%} {{ nav_card.rezervacija_nav_card() }}
<div class="card">
  <a href="{{url_for('rezervacija_routes.get_rezervacija_with_stol_data')}}">
    Sve
  </a>
  <input type="checkbox" name="active" id="active" disabled />
</div>
<div class="card">
  <table>
    <thead>
      <tr>
        <th>Rezervacija ID</th>
        <th>Ime</th>
        <th>Vrijeme</th>
        <th>Broj stola</th>
        <th>Lokacija stola</th>
      </tr>
    </thead>
    <tbody>
      {% for datapoint in data %}
      <tr>
        <td>{{ datapoint.id }}</td>
        <td>{{ datapoint.ime }}</td>
        <td>{{ datapoint.vrijeme }}</td>
        <td>{{ datapoint.broj_stola }}</td>
        <td>{{ datapoint.lokacija_stola }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/pages/rezervacija/rezervacija_by_location_with_count.html
{% extends "index.html" %} {% import
'components/nav-cards/rezervacija_nav_card.html' as nav_card %} {% block content
%} {{ nav_card.rezervacija_nav_card() }}
<div class="card">
  <table>
    <thead>
      <tr>
        <th>Restoran ID</th>
        <th>Lokacija stola</th>
        <th>Broj rezervacija</th>
      </tr>
    </thead>
    <tbody>
      {% for datapoint in data %}
      <tr>
        <td>{{ datapoint.restoran_id }}</td>
        <td>{{ datapoint.lokacija }}</td>
        <td>{{ datapoint.broj_rezervacija }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/pages/rezervacija/rezervacija_count_by_stol_location.html
{% extends "index.html" %} {% import
'components/nav-cards/rezervacija_nav_card.html' as nav_card %} {% block content
%} {{ nav_card.rezervacija_nav_card() }}
<div class="card">
  <table>
    <thead>
      <tr>
        <th>Lokacija stola</th>
        <th>Broj rezervacija</th>
      </tr>
    </thead>
    <tbody>
      {% for datapoint in data %}
      <tr>
        <td>{{ datapoint.lokacija_stola }}</td>
        <td>{{ datapoint.broj_rezervacija }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/pages/rezervacija/rezervacija_create.html
{% extends "index.html" %} {% block content %}
<h2>Dodaj rezervaciju:</h2>
<div class="card">
  <a href="{{url_for('rezervacija_routes.get_rezervacije')}}">Odustani</a>
</div>
<div class="card">
  <form
    class="create-form"
    action="{{url_for('rezervacija_routes.created_rezervacija')}}"
    method="POST"
    enctype="multipart/form-data"
  >
    {% if message %}
    <p class="error">{{message}}</p>
    {% endif %}
    <div class="form-input-group">
      <label for="restoran_id">Restoran:</label>
      <select
        name="restoran_id"
        id="restoran_id"
        required
        {%
        if
        restorani|length
      >
        0 %} value="{{restorani[0].id}}" {% endif %} > {% for restoran in
        restorani %}
        <option value="{{restoran.id}}">{{restoran.naziv}}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-input-group">
      <label for="stol_id">Stol:</label>
      <select name="stol_id" id="stol_id" required>
      {% if appropriate_stol_id is not none %}
        <option value="{{appropriate_stol_id}}" selected>
        stol {{appropriate_stol_id}} (pre-selected)
        </option>
      {% endif %}
      {% for stol in stolovi %}
        <option value="{{stol.id}}" {% if appropriate_stol_id == stol.id %}selected{% endif %}>
        stol {{stol.broj}}: {{stol.broj_mjesta}} mjesta
        </option>
      {% endfor %}
      </select>
    </div>
    <div class="form-input-group">
      <label for="ime">Ime:</label>
      <input type="text" name="ime" id="ime" required />
    </div>
    <div class="form-input-group">
      <label for="vrijeme">Vrijeme:</label>
      <input type="datetime-local" name="vrijeme" id="vrijeme" required />
    </div>
    <div class="form-input-group">
      <label for="broj_osoba">Broj osoba:</label>
      <input
        type="number"
        name="broj_osoba"
        id="broj_osoba"
        min="1"
        max="255"
        required
      />
    </div>
    <div class="form-input-group">
      <span></span>
      <input type="submit" value="Dodaj rezervaciju" />
    </div>
  </form>
</div>
<div class="card">
  <form
    class="create-form"
    action="{{url_for('rezervacija_routes.create_rezervacija')}}"
    method="GET"
  >
    <div class="form-input-group">
      <label for="restoran_id">Restoran:</label>
      <select name="restoran_id" id="restoran_id" required>
        {% for restoran in restorani %}
        <option value="{{restoran.id}}">{{restoran.naziv}}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-input-group">
      <label for="broj_mjesta">Broj Mjesta:</label>
      <input type="number" name="broj_mjesta" id="broj_mjesta" required>
    </div>
    <div class="form-input-group">
      <label for="lokacija">Lokacija:</label>
      <select name="lokacija" id="lokacija" required>
        <option value="unutra">Unutra</option>
        <option value="vani">Vani</option>
        <option value="vip">VIP</option>
      </select>
    </div>
    <div class="form-input-group">
      <button type="submit">Generiraj Stol</button>
    </div>
  </form>
</div>
{% endblock %}

app/templates/pages/rezervacija/rezervacija_update.html
{% extends "index.html" %} {% import 'components/buttons/view_item_button.html'
as view_item_button %} {% block content %}
<h2>Ažuriraj rezervaciju:</h2>
<div class="single-item-buttons card">
  {{
  view_item_button.view_item_button_link('rezervacija_routes.get_rezervacija',
  data.id, 'Odustani') }}
</div>
<div class="card">
  <form
    class="update-form"
    action="{{url_for('rezervacija_routes.updated_rezervacija', id=data.id)}}"
    method="POST"
    enctype="multipart/form-data"
  >
    <div class="form-input-group">
      <label for="restoran_id">Restoran:</label>
      <select
        name="restoran_id"
        id="restoran_id"
        required
        value="{{
        data.restoran_id}}"
      >
        {% for restoran in restorani %}
        <option value="{{restoran.id}}">{{restoran.naziv}}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-input-group">
      <label for="stol_id">Stol:</label>
      <select
        name="stol_id"
        id="stol_id"
        required
        value="{{
        data.stol_id}}"
      >
        {% for stol in stolovi %}
        <option value="{{stol.id}}">
          stol {{stol.broj}}: {{stol.broj_mjesta}} mjesta
        </option>
        {% endfor %}
      </select>
    </div>
    <div class="form-input-group">
      <label for="ime">Ime:</label>
      <input type="text" name="ime" id="ime" required value="{{data.ime}}" />
    </div>
    <div class="form-input-group">
      <label for="vrijeme">Vrijeme:</label>
      <input
        type="datetime-local"
        name="vrijeme"
        id="vrijeme"
        required
        value="{{
        data.vrijeme}}"
      />
    </div>
    <div class="form-input-group">
      <label for="broj_osoba">Broj osoba:</label>
      <input
        type="number"
        name="broj_osoba"
        id="broj_osoba"
        max="255"
        min="1"
        required
        value="{{data.broj_osoba}}"
      />
    </div>
    <div class="form-input-group">
      <span></span>
      <input type="submit" value="Ažuriraj rezervaciju" />
    </div>
  </form>
</div>
{% endblock %}

app/templates/pages/rezervacija/rezervacija_with_stol_data.html
{% extends "index.html" %} {% import
'components/nav-cards/rezervacija_nav_card.html' as nav_card %} {% block content
%} {{ nav_card.rezervacija_nav_card() }}
<div class="card">
  <table>
    <thead>
      <tr>
        <th>Rezervacija ID</th>
        <th>Ime</th>
        <th>Vrijeme</th>
        <th>Broj stola</th>
        <th>Lokacija stola</th>
      </tr>
    </thead>
    <tbody>
      {% for datapoint in data %}
      <tr>
        <td>{{ datapoint.id }}</td>
        <td>{{ datapoint.ime }}</td>
        <td>{{ datapoint.vrijeme }}</td>
        <td>{{ datapoint.broj_stola }}</td>
        <td>{{ datapoint.lokacija_stola }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/pages/rezervacija/rezervacije.html
{% import 'components/buttons/add_item_button.html' as add_item_button %} {%
import 'components/buttons/view_item_button.html' as view_item_button %} {%
import 'components/buttons/delete_item_button.html' as delete_item_button %} {%
extends "index.html" %} {% import
'components/nav-cards/rezervacija_nav_card.html' as nav_card %} {% block content
%} {{ nav_card.rezervacija_nav_card() }}
<div class="card">
  {{
  add_item_button.add_item_button_link('rezervacija_routes.create_rezervacija',
  'Dodaj rezervaciju') }}
</div>
<div class="card">
  <table>
    <thead>
      <tr>
        <th>Naziv restorana</th>
        <th>Broj stola</th>
        <th>Broj mjesta stola</th>
        <th>Ime</th>
        <th>Vrijeme</th>
        <th>Broj osoba</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for datapoint in data %}
      <tr>
        <td>{{ datapoint.naziv_restoran }}</td>
        <td>{{ datapoint.broj_stola }}</td>
        <td>{{ datapoint.broj_mjesta_stola }}</td>
        <td>{{ datapoint.ime }}</td>
        <td>{{ datapoint.vrijeme }}</td>
        <td>{{ datapoint.broj_osoba }}</td>
        <td class="button-cell">
          <div class="button-group">
            {{
            view_item_button.view_item_button_link('rezervacija_routes.get_rezervacija',
            datapoint.id, 'Pregledaj') }} {{
            delete_item_button.delete_item_button_form('rezervacija_routes.delete_rezervacija',
            datapoint.id, 'Obriši') }}
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}